### ISSUE TITLE
Add Scrollto on paginated results

### ISSUE THREAD

**Issue by budparr** [theNewDynamic/hugo-module-tnd-search#12]
In the search results modal we use pagination at the bottom of hits list. When clicking on the next page, the user should be taken to the top of the list. Can demo if necessary.

I _think_ this is what we want?
https://www.algolia.com/doc/api-reference/widgets/pagination/js/#widget-param-scrollto

**Comment by regisphilibert** [comment]
Any component parameter can be passed through the widget params so:

```yaml
  - name: pagination
    container: '#pagination_facets'
    scrollTo: header
    classes:
      root: my-4
      list: flex justify-center items-center
      item: mx-4
      link: text-blue-500 underline
      selectedItem: no-underline
```
