### ISSUE TITLE
Fix case being too script for id's produced by component name

### ISSUE THREAD

**Issue by regisphilibert** [theNewDynamic/hugo-module-tnd-search#7]
Currently 

```yaml
    widgets:
    - name: searchBox
      placeholder: 'Search'
```

Won't match `<div id="searchBox"></div>`
